// Store
1=Typing Magic
2=Typing Magic 12
1287=TypingMagic Typing Meter
18=TypingMagic.com
45=http://www.typingmagic.com
436=Please see the upgrade prices at www.typingmagic.com.
1030=For latest documentation, visit http://www.typingmagic.com
1072=More information at http://www.typingmagic.com
89=http://www.typingmagic.com
1902=http://www.typingmagic.com
717=Enter License Key
718=Please enter the License ID and Key found in your license email (check your spam folder) to activate your license. Your License ID is usually your order number.
720=License Key:
1806=Enter License Key
215=License Id or Key is typed incorrectly! Please type these codes carefully again. 
719=License Id:
211=Required information is missing. Please enter both the License ID
212=and the License Key to complete the license verification.
1487=View EULA
146=Welcome to Typing Magic
392=Welcome to Typing Magic touch typing tutor! Please give a user name below and click Enter.
1690=Welcome to Typing Magic
107=Thank you for test driving TypingMagic for 7 days! You will lose access to the paid features now but you can keep using the limited trial version and complete the free lessons. There are now also limitations in review, typing test and Typing Meter sections.\n\nYou can get full access to Typing Magic in minutes - just buy a license online. Click the buttons below for more information.
714=Product Information
303=Manage Your Product
1478=Manage My Order
551=Buy TypingMagic License
553=Update to Latest Version
519=\nTypingMagic's Typing Meter is an add-on that tracks your typing while you use your PC. It helps you improve by offering targeted drills for your weak keys and words.
1867=Uninstalling Typing Magic
735=Typing Configuration Profile
543=\+
544=\+
542=Welcome! Profile settings applied.
// Store
570=http://www.typingmagic.com/typing-tutor/order.html
713=Buy Now
717=Enter License Key
718=Please enter the License ID and Key found in your license email (check your spam folder) to activate your license. Your License ID is usually your order number.
720=License Key:
1806=Enter License Key
215=License Id or Key is typed incorrectly! Please type these codes carefully again. 
719=License Id:
211=Required information is missing. Please enter both the License ID
212=and the License Key to complete the license verification.
